### ISSUE TITLE
`Prodigy` Handle

### ISSUE THREAD

**Issue by b8zeek** [prodigy3k/mdmphp#1]
Greetings buddy,

I am in search for a GitHub handle which I can relate to. I was wondering if there's a chance that you would be willing to pass this one as you're inactive on GitHub? I would use it good!

Thanks in advance, do reach out, all of my contact information are on my page.

Take care! 🍺

🍀

**Comment by prodigy** [comment]
Hey hey,

Thank you for reminding me of this account, I'm actually using this one because prodigy was used. So I think I will migrate back to purely prodigy.

So thank you, now I can get rid of the 1 myself. ♥️

**Comment by b8zeek** [comment]
Hahaha... 😅 All right bro; enjoy using it and create some awesome stuff. :)

🍀
